name: Create branch from external dispatch

on:
  repository_dispatch:
    types: ['create_branch']

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo "${{ github.event.client_payload.version }}"